# Generated by Django 3.0.4 on 2020-03-06 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.IntegerField()),
                ('country_class', models.IntegerField()),
                ('code', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('ondate', models.DateTimeField(null=True)),
                ('offdate', models.DateTimeField(null=True)),
                ('issystem', models.IntegerField()),
                ('basison', models.CharField(max_length=1000)),
                ('basisoff', models.CharField(max_length=1000)),
                ('short', models.CharField(max_length=1000)),
                ('alpha2', models.CharField(max_length=1000)),
                ('alpha3', models.CharField(max_length=1000)),
                ('en', models.CharField(max_length=1000)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField()),
                ('payment_class', models.IntegerField()),
                ('code', models.CharField(max_length=1000)),
                ('ondate', models.DateTimeField(null=True)),
                ('offdate', models.DateTimeField(null=True)),
                ('issystem', models.IntegerField()),
                ('basison', models.CharField(max_length=1000)),
                ('basisoff', models.CharField(max_length=1000)),
                ('longdesc', models.TextField(max_length=5000)),
                ('paymenttype', models.IntegerField()),
                ('direction', models.IntegerField()),
                ('paymentcode', models.IntegerField()),
                ('feature', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='InExCoutry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_ex_type', models.CharField(max_length=1000)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.Country')),
                ('paymentstype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.PaymentsType')),
            ],
        ),
    ]
